HISTFILE=~/.zsh_history

export PATH=/opt/homebrew/lib/ruby/gems/3.3.0/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:$PATH
export PATH=$PATH:/usr/local/share/dotnet
export PATH="/Users/alexsvat/.local/bin:$PATH"

# plugins
if [ ! -d ~/.zgenom ]; then
    git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
fi
source "${HOME}/.zgenom/zgenom.zsh"
zgenom autoupdate
if ! zgenom saved; then
    zgenom load zsh-users/zsh-completions
    zgenom load zsh-users/zsh-syntax-highlighting
    zgenom load zsh-users/zsh-history-substring-search
    zgenom load jeffreytse/zsh-vi-mode
fi

# alias
alias v="nvim"
alias cm="cmatrix"
alias gt="git log --oneline --graph --decorate --all"
alias gq="git add -A && git commit -m \"changes\" && git push"
alias activate="python3 -m venv venv && source venv/bin/activate"

# default editor
export EDITOR="nvim"
export VISUAL="nvim"
export ZVM_VI_EDITOR="nvim"

# prompt

fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="%%"
PURE_PROMPT_VICMD_SYMBOL="%%"
PURE_CMD_MAX_EXEC_TIME=99999999
# single line 
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"
# NOTE: remove the print statement from ~/.zsh/pure/pure.zsh @ "Initial newline"

# command history
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt inc_append_history
# setopt share_history
setopt hist_ignore_dups
unsetopt share_history
setopt no_share_history
HISTORY_SUBSTRING_SEARCH_FUZZY='true'
bindkey -M viins "^[[A" history-substring-search-up
bindkey -M viins "^[[B" history-substring-search-down
bindkey -M vicmd "^[[A" history-substring-search-up
bindkey -M vicmd "^[[B" history-substring-search-down
bindkey '^P' history-beginning-search-backward
bindkey '^N' history-beginning-search-forward
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# command completion on tab
autoload -U compinit; compinit

# highlight items during tab completion
zstyle ':completion:*' menu select

# shift+tab to go up in autocomplete menu
# note: might have to run zsh -Y if this is not working
bindkey -M viins '^[[Z' reverse-menu-complete

# cd without typing 'cd'
setopt autocd

export CLICOLOR=1

prompt_for_tmux() {
	if read -q "?attach to tmux?"
	then
		tmux attach || tmux new-session -A -s whatever
	else
		clear
	fi
}

attach_to_tmux() {
	if [[ -n "$(tmux ls)" ]]
	then
		tmux attach
	else
		tmux new-session -A -s main 
	fi
}

# if [[ -z "$TMUX" ]]
# then
# 	prompt_for_tmux
# fi


# fzf
source <(fzf --zsh)

# TODO: not sure
# export PYENV_ROOT="$HOME/.pyenv"
# [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init - zsh)"

# yazi shortcut with auto-cd
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

